
package unisoft.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FNSNDSCAWS2", targetNamespace = "http://ws.unisoft", wsdlLocation = "http://npchk.nalog.ru/FNSNDSCAWS_2?wsdl")
public class FNSNDSCAWS2
    extends Service
{

    private final static URL FNSNDSCAWS2_WSDL_LOCATION;
    private final static QName FNSNDSCAWS2_QNAME = new QName("http://ws.unisoft", "FNSNDSCAWS2");

    static {
        URL url;
        try {
            url = new URL("http://npchk.nalog.ru/FNSNDSCAWS_2?wsdl");
        } catch (MalformedURLException ex) {
            throw new WebServiceException(ex);
        }
        FNSNDSCAWS2_WSDL_LOCATION = url;
    }

    public FNSNDSCAWS2() {
        super(FNSNDSCAWS2_WSDL_LOCATION, FNSNDSCAWS2_QNAME);
    }

    @WebEndpoint(name = "FNSNDSCAWS2_Port")
    public unisoft.ws.FNSNDSCAWS2Port getFNSNDSCAWS2Port() {
        return super.getPort(new QName("http://ws.unisoft", "FNSNDSCAWS2_Port"), FNSNDSCAWS2Port.class);
    }

}
